# Usamos un servidor web ultra ligero basado en Nginx
FROM nginx:alpine

# Copiamos el contenido estático de la aplicación al directorio raíz de Nginx
COPY index.html /usr/share/nginx/html/index.html
